apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: modresorts
  namespace: liberty
spec:
  applicationImage: 'docker.io/jtarte/app-modresort:2.2'
  applicationName: modresorts
  expose: true
  route:
    path: /resorts
  pullPolicy: IfNotPresent
  replicas: 1
  applicationVersion: '2.2'
