apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mybuildah
spec:
  params: 
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
  resources:
    inputs:
      - name: git-source
        type: git 
    outputs:
      - name: target-image
        type: image
  steps:
  - name: build-and-push
    image: quay.io/buildah/stable:latest
    workingDir: /workspace/git-source
    volumeMounts:
      - mountPath: /var/lib/containers
        name: varlibcontainers
    command: ["/bin/bash"]
    args:
      - -c
      - | 
        ls -al
        echo Build the image
        buildah bud --storage-driver=vfs -f $(inputs.params.DOCKERFILE) -t $(resources.outputs.target-image.url)
        echo Push the image
        buildah push  --storage-driver=vfs --creds=jtarte:fce9ce75-84e1-40d6-8aca-ffc3aeff5125 $(resources.outputs.target-image.url) docker://$(resources.outputs.target-image.url)
  volumes:
    - emptyDir: {}
      name: varlibcontainers
