apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mybuildah
spec:
  params: 
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
  resources:
    inputs:
      - name: git-source
        type: git 
    outputs:
      - name: target-image
        type: image
  steps:
  - name: build-and-push
    image: quay.io/buildah/stable:latest
    workingDir: /workspace/git-source
    env:
        - name: REG_USER
          valueFrom:
            secretKeyRef:
              name: dockerhub-secret
              key: user
        - name: REG_PWD
          valueFrom:
            secretKeyRef:
              name: dockerhub-secret
              key: token
    command: ["/bin/bash"]
    args:
      - -c
      - | 
        ls -al
        echo Build the image
        buildah bud --storage-driver=vfs -f $(inputs.params.DOCKERFILE) -t $(resources.outputs.target-image.url)
        echo Push the image
        buildah push  --storage-driver=vfs --creds=$(REG_USER):$(REG_PWD) $(resources.outputs.target-image.url) docker://$(resources.outputs.target-image.url)