apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: liberty-build-deploy
spec:
  workspaces:
    - name: workspace
  params:
    - name: script 
      description: "the yaml script used to deploy the application"
      type: string
    - name: git_url
      description: Git url
    - name: branch
      description: Revision to use
    - name: image
    - name: tag
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git_url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      runAfter:
        - checkout
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.image):$(params.tag)
      workspaces:
       - name: source
         workspace: workspace
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      workspaces:
        - name: manifest-dir
          workspace: workspace
      runAfter:
        - build
      params:
        - name: SCRIPT
          value: $(params.script)   
