kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-liberty
  namespace: liberty
subjects:
  - kind: ServiceAccount
    name: liberty-pipeline
    namespace: liberty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-rolebinding-liberty
  namespace: liberty
subjects:
  - kind: ServiceAccount
    name: liberty-pipeline
    namespace: liberty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole